const shuffle=a=>{const b=[...a];for(let i=b.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[b[i],b[j]]=[b[j],b[i]]}return b};
const words={days:[['Monday','pirmdiena'],['Tuesday','otrdiena'],['Wednesday','trešdiena'],['Thursday','ceturtdiena'],['Friday','piektdiena'],['Saturday','sestdiena'],['Sunday','svētdiena']],months:[['January','janvāris'],['February','februāris'],['March','marts'],['April','aprīlis'],['May','maijs'],['June','jūnijs'],['July','jūlijs'],['August','augusts'],['September','septembris'],['October','oktobris'],['November','novembris'],['December','decembris']],seasons:[['spring','pavasaris'],['summer','vasara'],['autumn','rudens'],['winter','ziema']]};
const pronouns=[['I','es'],['you','tu'],['he','viņš'],['she','viņa'],['it','tas'],['we','mēs'],['they','viņi']];
export function makeEnglishBank(){let bank=[];for(const [topic,pairs] of Object.entries(words)){pairs.forEach(([en,lv],i)=>{bank.push({id:topic+'-en-'+i,topic,q:'Iztulko angliski: '+lv,a:en,hint:'Atceries nosaukumu angļu valodā.'},{id:topic+'-lv-'+i,topic,q:'Iztulko latviski: '+en,a:lv,hint:'Atceries tulkojumu.'},{id:topic+'-order-'+i,topic,q:'Kurš nosaukums nāk pēc '+en+'?',a:pairs[(i+1)%pairs.length][0],hint:'Padomā par secību.'});});}
pronouns.forEach(([en,lv],i)=>bank.push({id:'pronoun-'+i,topic:'pronouns',q:'Iztulko angliski: '+lv,a:en,hint:'I, you, he, she, it, we, they.'}));
[['Anna is my friend. ___ is kind.','she'],['Dad is tall. ___ is strong.','he'],['Tom and I are friends. ___ play.','we'],['The cats are hungry. ___ want food.','they'],['This is a dog. ___ is happy.','it'],['___ am at school.','I'],['Are ___ ready?','you'],['Marta and Lisa sing. ___ sing well.','they'],['Mother reads. ___ likes books.','she'],['The boy runs. ___ is fast.','he']].forEach(([q,a],i)=>bank.push({id:'usage-'+i,topic:'pronouns',q,a,hint:'Nosaki, par kuru personu vai lietu ir runa.'}));return bank;}
export function renderMarksEnglish(root,{canSubmit=false,saveProgress=async()=>{}}={}){
 const host=document.createElement('section');host.className='module learning-hub';root.append(host);const bank=makeEnglishBank();
 const topics=[['days','📅 Nedēļas dienas'],['months','🗓️ Mēneši'],['seasons','🍁 Gadalaiki'],['pronouns','🧑 Personu vietniekvārdi']];
 let topic=null,items=[],index=0,correct=0,mode='practice',streak=0,best=0;
 const el=(tag,text)=>{let n=document.createElement(tag);if(text)n.textContent=text;return n};
 const button=(title,fn)=>{let b=el('button',title);b.type='button';b.className='action-button';b.onclick=fn;host.append(b);return b};
 function home(){host.replaceChildren();host.append(el('h2','🌍 Angļu valodas piedzīvojums'),el('p','Dienas, mēneši, gadalaiki un vietniekvārdi.'));topics.forEach(([id,title])=>button(title,()=>choose(id)));}
 function choose(id){topic=id;host.replaceChildren();host.append(el('h2',topics.find(t=>t[0]===id)[1]));button('🌱 Mācos · 8',()=>start('learn'));button('🎯 Trenējos · 12',()=>start('practice'));button('🏆 Pārbaudu sevi · 20',()=>start('exam'));button('← Priekšmeta tēmas',home);}
 function start(m){mode=m;items=shuffle(bank.filter(q=>q.topic===topic)).slice(0,m==='learn'?8:m==='exam'?20:12);index=correct=streak=best=0;step();}
 function step(){if(index===items.length){void finish();return;}host.replaceChildren();let q=items[index];host.append(el('h2','Jautājums '+(index+1)+' / '+items.length));let bar=el('div');bar.className='progress-track';let fill=el('div');fill.className='progress-fill';fill.style.width=(100*index/items.length)+'%';bar.append(fill);host.append(bar,el('p','🔥 '+streak+' pēc kārtas · Rekords: '+best),el('h3',q.q));let form=el('form');form.className='latvian-question-form';let inp=el('input');inp.type='text';inp.required=true;inp.autocomplete='off';inp.setAttribute('aria-label','Tava atbilde');form.append(inp);let submit=el('button','Pārbaudīt');submit.type='submit';form.append(submit);host.append(form);let status=el('p');status.setAttribute('role','status');host.append(status);if(mode==='learn')button('💡 Palīdzība',()=>status.textContent=q.hint);
 form.onsubmit=e=>{e.preventDefault();let good=inp.value.trim().toLocaleLowerCase('lv-LV')===q.a.toLocaleLowerCase('lv-LV');correct+=Number(good);streak=good?streak+1:0;best=Math.max(best,streak);inp.disabled=submit.disabled=true;status.textContent=mode==='exam'?'Atbilde saglabāta.':good?'✅ Pareizi!':'🔍 Pareizā atbilde: '+q.a;button('Nākamais →',()=>{index++;step()});};}
 async function finish(){let percent=Math.round(correct/items.length*100);host.replaceChildren();host.append(el('h2','Rezultāts: '+percent+'%'),el('p','Pareizi '+correct+' no '+items.length+' · Garākā sērija: '+best));let stat=el('p');host.append(stat);if(canSubmit)try{const id=await saveProgress({studentRole:'marks',subject:'Angļu valoda',activityType:topic+' · '+mode,score:percent,notes:JSON.stringify({correct,total:items.length,streak:best})});stat.textContent=id?'✅ Saglabāts Firebase':'⚠️ Nav apstiprināta saglabāšana';}catch{stat.textContent='⚠️ Saglabāšana neizdevās';}button('Atkārtot',()=>start(mode));button('← Tēmas',home);}
 home();
}