import {attachTouchNumpad} from './touch-numpad.js';
const shuffle=a=>{const x=[...a];for(let i=x.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[x[i],x[j]]=[x[j],x[i]];}return x;};
export function makeMarksMathBank(topic){
 const out=[];for(let a=1;a<=10;a++)for(let b=1;b<=10;b++){const n=a*b;
 const visual={groups:a,each:b,icon:['⭐','💎','🍎','🟣'][(a+b)%4]};
 if(topic==='multiply')out.push({id:'m'+a+'-'+b,prompt:a+' × '+b+' = ?',answer:n,hint:a+' grupas pa '+b+' = '+n});
 if(topic==='divide')out.push({id:'d'+a+'-'+b,prompt:n+' ÷ '+a+' = ?',answer:b,hint:'Pārbaudi: '+a+' × '+b+' = '+n});
 if(topic==='family'){out.push({id:'f1-'+a+'-'+b,prompt:a+' × '+b+' = ?',answer:n,hint:'Šī pati skaitļu saime: '+n+' ÷ '+a+' = '+b});out.push({id:'f2-'+a+'-'+b,prompt:n+' ÷ '+b+' = ?',answer:a,hint:'Atceries: '+a+' × '+b+' = '+n});out.push({id:'f3-'+a+'-'+b,prompt:a+' × □ = '+n,answer:b,hint:'Nosaki nezināmo reizinātāju'});}
 if(topic==='story'){out.push({id:'s1-'+a+'-'+b,prompt:'Pūķis atrada '+a+' lādes. Katrā lādē ir '+b+' kristāli. Cik kristālu kopā?',answer:n,hint:'Reizini lādes ar kristālu skaitu.',visual});out.push({id:'s2-'+a+'-'+b,prompt:n+' kristālus vienādi sadalīja '+a+' kastēs. Cik kristālu ir katrā kastē?',answer:b,hint:'Sadali visus kristālus kastēs.',visual});}
 }return out;
}
export function renderMarksMath(root,{canSubmit=false,saveProgress=async()=>{}}={}){
 const host=document.createElement('section');host.className='module learning-hub marks-math';root.append(host);
 const topics=[['multiply','⚔️ Reizrēķins','Reizināšana 1–10, rezultāti līdz 100'],['divide','🛡️ Dalīšana','Dalīšana bez atlikuma'],['family','🔗 Saistītais pieraksts','Reizināšanas un dalīšanas saimes'],['story','🐉 Teksta misijas','Uzdevumi ar kristālu grupām']];
 const el=(tag,txt)=>{const e=document.createElement(tag);if(txt!==undefined)e.textContent=txt;return e;};
 const btn=(parent,txt,fn)=>{const b=el('button',txt);b.type='button';b.className='action-button';b.onclick=fn;parent.append(b);return b;};
 let chosen='',mode='',items=[],position=0,correct=0,streak=0,record=0,errors=[];
 function head(title,desc){host.replaceChildren();const h=el('div');h.className='learning-heading';h.append(el('span','🐉 MARKA MATEMĀTIKA'),el('h2',title),el('p',desc));host.append(h);}
 function home(){head('Skaitļu misijas','Izvēlies misiju un trenējies savā ritmā.');const grid=el('div');grid.className='topic-grid';host.append(grid);for(const [id,name,desc] of topics){const b=el('button');b.type='button';b.className='topic-tile';b.append(el('span',name.split(' ')[0]),el('strong',name.slice(name.indexOf(' ')+1)),el('small',desc));b.onclick=()=>choose(id);grid.append(b);}}
 function choose(id){chosen=id;const label=topics.find(t=>t[0]===id);head(label[1],label[2]);btn(host,'🌱 Mācos · 8',()=>start('learn'));btn(host,'🎯 Trenējos · 12',()=>start('practice'));btn(host,'🏆 Pārbaudu sevi · 20',()=>start('exam'));btn(host,'← Misijas',home);}
 function start(m,review=false){mode=review?'review':m;const all=makeMarksMathBank(chosen);const different=review?all.filter(q=>!errors.some(e=>e.id===q.id)):all;items=shuffle(different).slice(0,review?10:m==='learn'?8:m==='exam'?20:12);position=correct=streak=record=0;errors=[];step();}
 function step(){if(position>=items.length){void finish();return;}const q=items[position];head('Misija '+(position+1)+' no '+items.length,'Atrisini un turpini savu sēriju.');const progress=el('div');progress.className='progress-track';const fill=el('div');fill.className='progress-fill';fill.style.width=Math.round(position/items.length*100)+'%';progress.append(fill);host.append(progress);const count=el('p','🔥 '+streak+' pēc kārtas · Rekords '+record);count.className='streak-label';host.append(count);const card=el('div');card.className='question-stage';card.append(el('div',q.prompt));card.firstChild.className='math-expression';if(q.visual){const groups=el('div');groups.className='visual-groups';groups.setAttribute('role','img');groups.setAttribute('aria-label',q.visual.groups+' grupas pa '+q.visual.each);for(let i=0;i<q.visual.groups;i++){const g=el('div');g.className='visual-group';for(let j=0;j<q.visual.each;j++){const icon=el('span',q.visual.icon);icon.className='visual-object';g.append(icon);}groups.append(g);}card.append(groups);}const form=el('form');form.className='math-answer-form';const input=el('input');input.type='number';input.inputMode='numeric';input.required=true;input.min=0;input.max=100;input.step=1;input.className='big-number-input';input.setAttribute('aria-label','Tava atbilde');const submit=el('button','Pārbaudīt');submit.type='submit';submit.className='action-button';form.append(input,submit);card.append(form);const status=el('p');status.setAttribute('role','status');card.append(status);const numpad=attachTouchNumpad(card,input);host.append(card);if(mode==='learn')btn(card,'💡 Pavediena palīdzība',()=>{status.textContent=q.hint;});form.onsubmit=e=>{e.preventDefault();const value=Number(input.value);if(input.value===''||!Number.isInteger(value))return;const ok=value===q.answer;correct+=Number(ok);streak=ok?streak+1:0;record=Math.max(record,streak);if(!ok)errors.push(q);input.disabled=submit.disabled=true;numpad.querySelectorAll('button').forEach(b=>b.disabled=true);status.textContent=mode==='exam'?'Atbilde pieņemta.':ok?'✅ Pareizi!':'🔎 '+q.hint;btn(card,'Nākamais →',()=>{position++;step();});};}
 async function finish(){const pct=Math.round(correct/items.length*100);head('Misija pabeigta!','Katrs mēģinājums nostiprina prasmes.');const score=el('div',pct+'%');score.className='result-hero';host.append(score,el('p',correct+' / '+items.length+' pareizi · Garākā sērija '+record));const note=el('p');host.append(note);if(canSubmit){try{const id=await saveProgress({studentRole:'marks',subject:'Matemātika',activityType:chosen+' · '+mode,score:pct,notes:JSON.stringify({correct,total:items.length,bestStreak:record})});note.textContent=id?'✅ Rezultāts saglabāts Firebase.':'⚠️ Nav apstiprināta saglabāšana.';}catch{note.textContent='⚠️ Saglabāšana neizdevās.';}}if(errors.length){btn(host,'🎯 Trenēt kļūdas ar citiem piemēriem',()=>start(mode,true));}btn(host,'Atkārtot misiju',()=>start(mode));btn(host,'← Uz tēmām',home);}
 home();
}