const examples=[['Kaķis guļ uz sola.','Kur guļ kaķis?','uz sola'],['Saule spīd.','Kas spīd?','saule'],['Liene lasa grāmatu.','Ko lasa Liene?','grāmatu'],['Dārzā aug roze.','Kas aug dārzā?','roze'],['Mazs suns skrien.','Kas skrien?','suns'],['Tētis cep maizi.','Ko cep tētis?','maizi'],['Mežā dzīvo lapsa.','Kur dzīvo lapsa?','mežā'],['Anna dzer pienu.','Ko dzer Anna?','pienu'],['Putns dzied kokā.','Kur dzied putns?','kokā'],['Zivis peld ezerā.','Kur peld zivis?','ezerā'],['Māsa zīmē puķi.','Ko zīmē māsa?','puķi'],['Pele grauž sieru.','Ko grauž pele?','sieru'],['Sniegs klāj zemi.','Kas klāj zemi?','sniegs'],['Lācis guļ alā.','Kur guļ lācis?','alā'],['Mamma nes somu.','Ko nes mamma?','somu'],['Bērni spēlējas parkā.','Kur spēlējas bērni?','parkā'],['Vilciens brauc ātri.','Kas brauc ātri?','vilciens'],['Skolā skan zvans.','Kas skan skolā?','zvans']];
const partWords={lietvārds:['māja','suns','zieds','koks','laiva','upe','skola','grāmata','pele','saule'],darbības_vārds:['skrien','lasa','ēd','raksta','dzied','lec','sēž','brauc','zīmē','peld'],īpašības_vārds:['mazs','liels','gudrs','gaišs','zaļš','skaists','silts','garš','sarkans','ātrs']};
const gaps=[['m_ja','ā'],['sk_la','o'],['p_ķe','u'],['z_eds','i'],['lā_is','c'],['gr_mata','ā'],['s_ule','a'],['m_žs','e'],['sni_gs','e'],['m_ļš','ī'],['r_tenis','i'],['z_mulis','ī'],['b_rns','ē'],['r_denī','u'],['pļ_va','a'],['dra_gs','u'],['m_konis','ā']];
export function makeSamantaLatvianBank(){let bank=[];examples.forEach(([sentence,question,answer],i)=>bank.push({id:'r'+i,topic:'reading',q:sentence+'\n'+question,a:answer,hint:'Izlasi pirmo teikumu vēlreiz.'}));for(const [name,words] of Object.entries(partWords))words.forEach((word,i)=>bank.push({id:'p'+name+i,topic:'parts',q:'Kura vārdšķira ir vārds “'+word+'”?',a:name.replace('_',' '),hint:'Lietvārds ir lieta; darbības vārds ir darbība; īpašības vārds ir pazīme.'}));gaps.forEach(([word,answer],i)=>bank.push({id:'g'+i,topic:'letters',q:'Ievieto trūkstošo burtu: '+word,a:answer,hint:'Izrunā vārdu lēnām un padomā par skaņu.'}));return bank;}
export function renderSamantaLatvian(root,{canSubmit=false,saveProgress=async()=>{}}={}){
 const host=document.createElement('section');host.className='module learning-hub samanta-reading';root.append(host);const bank=makeSamantaLatvianBank();
 const topics=[['reading','📖 Vieglā lasīšana'],['parts','🧩 Vārdšķiras'],['letters','🔤 Trūkstošais burts']];let topic=null,mode='practice',questions=[],index=0,correct=0,streak=0,maxStreak=0;
 const el=(tag,text)=>{let n=document.createElement(tag);if(text)n.textContent=text;return n};
 const btn=(text,cb,parent=host,cls='action-button')=>{const b=el('button',text);b.type='button';b.className=cls;b.onclick=cb;parent.append(b);return b};
 const shuffle=x=>[...x].sort(()=>Math.random()-.5);
 function view(){host.replaceChildren();host.append(el('h2','🌸 Latviešu valodas dārzs'),el('p','Lasi, klausies un trenējies savā ritmā.'));topics.forEach(([key,title])=>btn(title,()=>choose(key)));}
 function choose(t){topic=t;host.replaceChildren();host.append(el('h2',topics.find(x=>x[0]===t)[1]));btn('🌱 Mācos · 8',()=>start('learn'));btn('🎯 Trenējos · 12',()=>start('practice'));btn('🏆 Pārbaudu sevi · 20',()=>start('exam'));btn('← Visas tēmas',view);}
 function start(m){mode=m;questions=shuffle(bank.filter(q=>q.topic===topic)).slice(0,m==='learn'?8:m==='exam'?20:12);index=correct=streak=maxStreak=0;step();}
 function step(){if(index>=questions.length){void finish();return;}host.replaceChildren();let q=questions[index];host.append(el('h2','Uzdevums '+(index+1)+' no '+questions.length));let progress=el('div');progress.className='progress-track';let fill=el('div');fill.className='progress-fill';fill.style.width=(index/questions.length*100)+'%';progress.append(fill);host.append(progress);const streakBadge=el('p','🔥 '+streak+' pareizas pēc kārtas · Rekords: '+maxStreak);streakBadge.className='streak-label';host.append(streakBadge);const card=el('section');card.className='reading-task-card';const taskText=el('div',q.q);taskText.className='reading-prompt';taskText.style.whiteSpace='pre-line';card.append(taskText);host.append(card);const status=el('p');status.setAttribute('role','status');status.className='reading-feedback';const controls=el('div');controls.className='reading-controls';
 btn('🔊 Nolasīt uzdevumu',()=>{if(!('speechSynthesis'in window)){status.textContent='Balss nolasīšana šajā pārlūkā nav pieejama.';return;}window.speechSynthesis.cancel();let u=new SpeechSynthesisUtterance(q.q);u.lang='lv-LV';u.rate=.82;const v=window.speechSynthesis.getVoices().find(v=>v.lang.startsWith('lv'));if(v)u.voice=v;window.speechSynthesis.speak(u);},controls,'reading-listen');btn('⏹ Apturēt',()=>{if('speechSynthesis'in window)window.speechSynthesis.cancel();},controls,'reading-stop');card.append(controls);
 const form=el('form');form.className='reading-answer-form';const label=el('label','Tava atbilde');label.className='reading-answer-label';const input=el('input');input.className='reading-answer-input';input.id='samanta-reading-answer';label.htmlFor=input.id;input.required=true;input.autocomplete='off';input.setAttribute('aria-label','Tava atbilde');input.maxLength=80;form.append(label,input);let submit=el('button','Pārbaudīt');submit.type='submit';submit.className='action-button';form.append(submit);card.append(form,status);if(mode==='learn')btn('💡 Palīdzība',()=>status.textContent=q.hint);
 form.onsubmit=e=>{e.preventDefault();const answer=input.value.trim().toLocaleLowerCase('lv-LV');const good=answer===q.a.toLocaleLowerCase('lv-LV');correct+=Number(good);streak=good?streak+1:0;maxStreak=Math.max(streak,maxStreak);input.disabled=submit.disabled=true;status.textContent=mode==='exam'?'Atbilde saglabāta.':good?'✅ Pareizi!':'🔎 Pamēģini atcerēties: '+q.a;btn('Nākamais →',()=>{index++;step();});};}
 async function finish(){if('speechSynthesis'in window)window.speechSynthesis.cancel();const pct=Math.round(100*correct/questions.length);host.replaceChildren();host.append(el('h2','Rezultāts: '+pct+'%'),el('p','Pareizi '+correct+' no '+questions.length+' · Sērija: '+maxStreak));let status=el('p');host.append(status);if(canSubmit)try{const id=await saveProgress({studentRole:'samanta',subject:'Latviešu valoda',activityType:topic+' · '+mode,score:pct,notes:JSON.stringify({correct,total:questions.length,maxStreak})});status.textContent=id?'✅ Rezultāts saglabāts Firebase':'⚠️ Saglabāšana nav apstiprināta';}catch{status.textContent='⚠️ Saglabāšana neizdevās';}btn('Mēģināt vēlreiz',()=>start(mode));btn('← Tēmas',view);}
 view();
}